import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  fpsfSidebar: [{ type: 'autogenerated', dirName: '.' }]

  //fpsfSidebar: [
  //    {
  //      type: 'category',
  //  label: 'Specifications',
  //      items: [
  // {
  //   type: 'category',
  //   label: 'Stablecoin Stack',
  //   items: [{
  //     type: 'autogenerated',
  //     dirName: 'specs/ssf',
  //   }],
  // },
  // {
  //   type: 'category',
  //   label: 'CashPack',
  //   items: [{
  //     type: 'autogenerated',
  //     dirName: 'specs/cashpack',
  //   }],
  //}
  //],
  // },
  // {
  //   // Keep autogeneration for the clean folder
  //   type: 'category',
  //   label: 'Implementation',
  //   items: [{
  //     type: 'autogenerated',
  //     dirName: 'impl',
  //   }],
  // },
  // {
  //   type: 'category',
  //   label: 'FAQ',
  //   items: [{
  //     type: 'autogenerated',
  //     dirName: 'faq',
  //   }]
  // },
  // ],

  // ssfCustomSidebar: [

  //   {
  //     type: 'autogenerated',
  //     dirName: 'vision-principles',
  //   },
  //   // Manual entry for the long-named specs
  //   {
  //     type: 'category',
  //     label: 'Specifications',
  //     items: [
  //       //000
  //       {
  //         type: 'doc',
  //         id: 'specs/ssf-specs-000/the-stablecoin-stack-overview-and-architecture',
  //         label: '000 - System Overview and Architecture'
  //       },
  //       //001
  //       {
  //         type: 'doc',
  //         id: 'specs/ssf-specs-001/instant-payment-with-permitted-token-transfer-submission',
  //         label: '001 - Payment Submission'
  //       },
  //       //002
  //       {
  //         type: 'doc',
  //         id: 'specs/ssf-specs-002/settlement-contract',
  //         label: '002 - The Settlement Contract'
  //       },
  //     ],
  //   },
  //   {
  //     // Keep autogeneration for the clean folder
  //     type: 'category',
  //     label: 'Implementation',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'impl',
  //     }],
  //   },
  //   {
  //     // Keep autogeneration for the clean folder
  //     type: 'category',
  //     label: 'Layers',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'layers',
  //     }],
  //   },
  //   {
  //     type: 'category',
  //     label: 'FAQ',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'faq',
  //     }]
  //   },
  // ],
};

export default sidebars;

